### ISSUE TITLE
nuget: Common release missing for Npgsql

### ISSUE THREAD

**Issue by crystalgreen** [NotCoffee418/DapperBulkQueries#4]
I am trying to install the nuget package [DapperBulkQueries.Npgsql](https://www.nuget.org/packages/DapperBulkQueries.Npgsql) with version `1.8970.14056` which requires the dependency [DapperBulkQueries.Common](https://www.nuget.org/packages/DapperBulkQueries.Common/) (>= 1.8970.14056).
However, at time of writing, the latest published [Common](https://www.nuget.org/packages/DapperBulkQueries.Common) version is 1.8970.14055, according to nuget.
Could you please publish a compatible version of that package?

**Comment by NotCoffee418** [comment]
Hmm that's concerning. I've pushed a new version that reduces the chance of this happening, but I'll have to find a better way to do automatic versioning down the line because there's still some 1% chance every build of this happening.
Thanks for letting me know about this.

**Comment by crystalgreen** [comment]
You could use a tool like [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) do do semi-automatic versioning.
